name: Build Android App
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Unzip project
        run: |
          unzip -o Zameen-Hisab.zip
          if [! -f package.json ]; then
            for d in */; do
              if [ -f "$d/package.json" ]; then
                cp -r "$d"/*.
                break
              fi
            done
          fi
          ls -la

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install Project Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Generate Android Project
        run: npx expo prebuild --platform android --clean --non-interactive

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
         ./gradlew assembleRelease

      - name: Build AAB
        run: |
          cd android
         ./gradlew bundleRelease

      - name: Upload APK and AAB
        uses: actions/upload-artifact@v4
        with:
          name: Zameen-Hisab-APK-AAB
          path: |
            android/app/build/outputs/apk/release/*.apk
            android/app/build/outputs/bundle/release/*.aab
